services:
  postgres:
    image: postgres:16-alpine
    container_name: dashboard-vpn-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: vpn_admin
      POSTGRES_PASSWORD: vpn_admin
      POSTGRES_DB: dashboard_vpn
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
