FROM node:20-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/bot ./apps/bot

RUN npm ci
WORKDIR /app/apps/bot
RUN npm run build

FROM node:20-bookworm-slim

WORKDIR /app/apps/bot

COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/apps/bot/dist ./dist
COPY --from=build /app/apps/bot/package.json ./package.json

ENV NODE_ENV=production

CMD ["node", "dist/index.js"]
